# Generated by Django 5.0 on 2025-10-04 21:46

import django.db.models.deletion
from django.conf import settings
"""Generated by Django 5.0 on 2025-10-04 21:46

This migration file creates the Profile, Education, Project, WorkExperience, and Skill
models for the `profiles` app. It was generated by Django and should be run by
`python manage.py migrate`.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('recruiter', 'Recruiter'), ('regular', 'Job Seeker'), ('admin', 'Admin')], default='regular', max_length=10)),
                ('headline', models.CharField(blank=True, help_text='Professional headline or title', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Brief professional summary')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, help_text='Candidate location', max_length=255)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('portfolio_url', models.URLField(blank=True, help_text='Personal website or portfolio URL')),
                ('skills_text', models.TextField(blank=True, default='', help_text='Comma-separated list of skills (simple version)')),
                ('projects_text', models.TextField(blank=True, default='', help_text='Short description/list of projects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public - Visible to everyone'), ('recruiters', 'Recruiters Only - Visible to recruiters and admins'), ('private', 'Private - Only visible to me')], default='recruiters', help_text='Control who can see your profile', max_length=20)),
                ('show_contact_info', models.BooleanField(default=True, help_text='Show phone and email to viewers')),
                ('show_skills', models.BooleanField(default=True, help_text='Show skills section')),
                ('show_education', models.BooleanField(default=True, help_text='Show education section')),
                ('show_experience', models.BooleanField(default=True, help_text='Show work experience section')),
                ('show_links', models.BooleanField(default=True, help_text='Show social/portfolio links')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently studying', null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('description', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='profiles.profile')),
            ],
            options={
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Describe the project and your role')),
                ('technologies', models.CharField(blank=True, help_text='Technologies used (comma-separated)', max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if ongoing', null=True)),
                ('project_url', models.URLField(blank=True, help_text='Link to project (GitHub, live demo, etc.)')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this project on profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profiles.profile')),
            ],
            options={
                'ordering': ['-is_featured', '-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently working', null=True)),
                ('description', models.TextField(blank=True, help_text='Describe your responsibilities and achievements')),
                ('is_current', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='profiles.profile')),
            ],
            options={
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.profile')),
            ],
            options={
                'unique_together': {('profile', 'name')},
            },
        ),
    ]
