# Generated by Django 5.0 on 2025-10-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for recruiters to contact you', max_length=254),
        ),
    ]
