# Generated by Django 5.0 on 2025-10-05 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_job_is_remote_job_skills_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('review', 'Under Review'), ('interview', 'Interview'), ('offer', 'Offer'), ('closed', 'Closed')], default='applied', max_length=20)),
                ('cover_note', models.TextField(blank=True, help_text='Personalized note from the applicant')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewed_by_recruiter', models.BooleanField(default=False)),
                ('recruiter_notes', models.TextField(blank=True, help_text='Internal notes from recruiter')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('applicant', 'job')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('applied', 'Applied'), ('review', 'Under Review'), ('interview', 'Interview'), ('offer', 'Offer'), ('closed', 'Closed')], max_length=20)),
                ('new_status', models.CharField(choices=[('applied', 'Applied'), ('review', 'Under Review'), ('interview', 'Interview'), ('offer', 'Offer'), ('closed', 'Closed')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Application status histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
