# Generated by Django 5.0 on 2025-09-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_recreate_job_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_remote',
            field=models.BooleanField(default=False, help_text='Is this a remote position?'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True, help_text='Required skills (comma-separated)'),
        ),
        migrations.AddField(
            model_name='job',
            name='visa_sponsorship',
            field=models.BooleanField(default=False, help_text='Does this job offer visa sponsorship?'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full-time', max_length=20),
        ),
    ]
