# Generated by Django 5.0 on 2025-11-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_is_remote_job_skills_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of job location', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of job location', null=True),
        ),
    ]
