# Generated by Django 5.0 on 2025-09-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Candidate location', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.TextField(blank=True, default='', help_text='Short description/list of projects'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of skills'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('regular', 'Job Seeker'), ('admin', 'Admin')], default='regular', max_length=10),
        ),
    ]
