# Generated by Django 5.0 on 2025-09-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_bio_profile_created_at_profile_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('recruiters', 'Recruiters Only - Visible to recruiters and admins'), ('private', 'Private - Only visible to me')], default='recruiters', help_text='Control who can see your profile', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_contact_info',
            field=models.BooleanField(default=True, help_text='Show phone and email to viewers'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_education',
            field=models.BooleanField(default=True, help_text='Show education section'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_experience',
            field=models.BooleanField(default=True, help_text='Show work experience section'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_links',
            field=models.BooleanField(default=True, help_text='Show social/portfolio links'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_skills',
            field=models.BooleanField(default=True, help_text='Show skills section'),
        ),
    ]
