# Generated by Django 5.0 on 2025-09-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_profile_visibility_profile_show_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.TextField(blank=True, default='', help_text='Short description/list of projects'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_text',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of skills (simple version)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='Candidate location', max_length=255),
        ),
    ]
