# Generated by Django 5.0 on 2025-09-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_projects_profile_skills_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_projects',
            field=models.BooleanField(default=True, help_text='Show projects section'),
        ),
    ]
