# Generated by Django 5.0 on 2025-09-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_create_project_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='show_projects',
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.TextField(blank=True, default='', help_text='Short description/list of projects'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_text',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of skills (simple version)'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
