# Generated by Django 5.0 on 2025-09-28 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_show_projects_profile_projects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='projects',
            new_name='projects_text',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Describe the project and your role')),
                ('technologies', models.CharField(blank=True, help_text='Technologies used (comma-separated)', max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if ongoing', null=True)),
                ('project_url', models.URLField(blank=True, help_text='Link to project (GitHub, live demo, etc.)')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this project on profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.profile')),
            ],
            options={
                'ordering': ['-is_featured', '-end_date', '-start_date'],
            },
        ),
    ]
