# Generated by Django 5.0 on 2025-10-26 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_alter_application_unique_together'),
        ('jobs', '0003_job_is_remote_job_skills_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='jobs.job')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('job', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CandidateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_card', to='applications.application')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='recruiter.stage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('stage', 'order')},
            },
        ),
    ]
