# Generated by Django 5.0 on 2025-11-22 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this saved search', max_length=200)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated skills', max_length=500)),
                ('location', models.CharField(blank=True, help_text='Location filter', max_length=255)),
                ('projects', models.CharField(blank=True, help_text='Projects keywords', max_length=500)),
                ('general_search', models.CharField(blank=True, help_text='General search query', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('recruiter', 'name')},
            },
        ),
    ]
