# Generated by Django 5.0 on 2025-11-21 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_job_is_remote_job_skills_required_and_more'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0, help_text='Overall match score (0-100)')),
                ('skills_match_score', models.FloatField(default=0.0, help_text='Skills match percentage')),
                ('experience_match_score', models.FloatField(default=0.0, help_text='Experience level match')),
                ('location_match_score', models.FloatField(default=0.0, help_text='Location match score')),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('viewed_by_recruiter', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False, help_text='Marked as favorite by recruiter')),
                ('recruiter_notes', models.TextField(blank=True, help_text="Recruiter's notes about this candidate")),
                ('status', models.CharField(choices=[('new', 'New Recommendation'), ('viewed', 'Viewed'), ('contacted', 'Contacted'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to=settings.AUTH_USER_MODEL)),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='profiles.profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='jobs.job')),
            ],
            options={
                'ordering': ['-match_score', '-recommended_at'],
                'indexes': [models.Index(fields=['job', '-match_score'], name='recommendat_job_id_603c66_idx'), models.Index(fields=['job', 'status'], name='recommendat_job_id_5f814b_idx')],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
